# Build container for Mirage 'static_website' example.

# Build distro must match that used to build 'mir-runner'.
FROM ocaml/opam:alpine

RUN opam depext -i mirage
RUN git clone http://github.com/mirage/mirage-skeleton
WORKDIR /home/opam/mirage-skeleton/static_website
RUN opam config exec -- mirage configure --unix
RUN opam config exec make

# "Run" phase outputs built unikernel as a .tar.gz.
CMD tar -C /home/opam/mirage-skeleton/static_website -czh -f - mir-www
