FROM mato/rumprun-toolchain-hw-x86_64:wip-rumprun-config

ADD ./wopr/wopr.c /build/
WORKDIR /build
RUN x86_64-rumprun-netbsd-gcc -O2 -o wopr wopr.c
RUN mkdir -p /build/unikernel /build/unikernel/fs && \
    rumprun-bake hw_virtio /build/unikernel/unikernel.bin wopr && \
    x86_64-rumprun-netbsd-strip /build/unikernel/unikernel.bin

WORKDIR /build/unikernel
CMD tar -czf - *
