# Runtime container for Mirage 'stackv4' example (ukvm version).

FROM mir-runner
ADD mir-stackv4-ukvm.tar.gz /unikernel/

# ENTRYPOINT is already set by mir-runner.
CMD ["ukvm", "/unikernel/mir-stackv4.ukvm"]
