# Build container for Mirage 'stackv4' example (ukvm version).

# Build distro must match that used to build 'mir-runner'.
FROM ocaml/opam:alpine-3.4_ocaml-4.03.0

# Workaround for issue with current opam:alpine images.
RUN sudo apk add --no-cache ncurses-dev

# Solo5 packages are not upstreamed yet.
RUN opam repo add solo5 git://github.com/solo5/opam-solo5
RUN opam depext -i mirage
RUN git clone http://github.com/mirage/mirage-skeleton
WORKDIR /home/opam/mirage-skeleton/stackv4
RUN opam config exec -- mirage configure --ukvm
RUN opam config exec make
# runner expects ukvm binary in /unikernel/ukvm
RUN cp ./ukvm-bin ./ukvm

# "Run" phase outputs built unikernel and ukvm as a .tar.gz.
CMD tar -C /home/opam/mirage-skeleton/stackv4 -czh -f - \
    ukvm \
    mir-stackv4.ukvm
