# Runtime container for Mirage 'stackv4' example (qemu version).

FROM mir-runner-qemu
ADD mir-stackv4-virtio.tar.gz /unikernel/

# ENTRYPOINT is already set by mir-runner.
CMD ["qemu", "/unikernel/mir-stackv4.virtio"]
