# Build container for Mirage 'stackv4' example (ukvm version).

# Build distro must match that used to build 'mir-runner'.
FROM ocaml/opam:alpine-3.4_ocaml-4.03.0

# Mirage/Solo5 is not released yet.
RUN opam repo add mirage-dev git://github.com/mirage/mirage-dev
RUN opam depext -i mirage
RUN git clone -b mirage-dev http://github.com/mirage/mirage-skeleton
WORKDIR /home/opam/mirage-skeleton/stackv4

# Until we have a fix for mirage/mirage#703 not installing depexts, install
# them manually.
RUN sudo apk add --no-cache linux-headers

RUN opam config exec -- mirage configure -t ukvm
RUN opam config exec make depend
RUN opam config exec make
# runner expects ukvm binary in /unikernel/ukvm
RUN cp ./ukvm-bin ./ukvm

# "Run" phase outputs built unikernel and ukvm as a .tar.gz.
CMD tar -C /home/opam/mirage-skeleton/stackv4 -czh -f - \
    ukvm \
    mir-stackv4.ukvm
